import type { NextPage } from "next";
import Head from "next/head";

import styles from "../styles/Home.module.css";
import { Header, HomeBanner } from "../components";

const HomePage: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Fashion Store</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
      <HomeBanner />
    </div>
  );
};

export default HomePage;
