import { PageTitle } from "components";
import type { NextPage } from "next";
import Head from "next/head";

const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Admin Panel - 420 Vogue</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <PageTitle routes={["Dashboard"]} />
    </div>
  );
};

export default Home;
