import type { NextPage } from "next";
import Head from "next/head";

import styles from "../styles/Home.module.css";
import { Header } from "components";

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Admin Panel - 420 Vogue</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Header />
      <h3>Admin</h3>
    </div>
  );
};

export default Home;
