# This is a basic workflow to help you get started with Actions
name: deploy-admin-client

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    paths:
      - 'admin-client/**'
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v1
        with:
          node-version: 16
          
      
          
      - name: Install yarn
        run: npm install -g yarn
        
      - name: PWD
        run: pwd
        
      - name: List 1
        run: ls
        
      - name: Navigate to admin-client
        run: cd ./admin-client
      
      - name: Install dependencies with frozen lockfile
        run: yarn install --frozen-lockfile
        
      - name: List
        run: ls
        
      - name: Build
        run: yarn build
      
      
      - uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.S3_SYNC_AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.S3_SYNC_AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-south-1
      
      - name: Sync with S3
        run: aws s3 sync ./out s3://mpanel.420vogue.in
